### ISSUE TITLE
Customizing PR Prefix

### ISSUE THREAD

**Issue by rustydb** [Cray-HPE/backport-command-action#3]
It would be nice to have a way to customize or omit the prefix that's prepended to the backport PR.

For example, when we merge backports to docs-csm the PR title is included as the merge's commit message. The commit messages would be cleaner if the PR titled omitted the `[backport release/1.0]` prefix:
- We already know it is targeting release/1.0 by the context of the base branch
- Knowing it is a backport doesn't necessarily imply anything, the change is really logged by the JIRA

**Comment by mtupitsyn** [comment]
I believe at least `[release/1.0]` part is still needed. Otherwise, it will be literally impossible to distinguish  betweeb PR's for different branches in the [PR list](https://github.com/Cray-HPE/docs-csm/pulls). For each PR, [PR list](https://github.com/Cray-HPE/docs-csm/pulls) displays title, status and labels, but it does not display branch names.
